// Shared HTML renderer: the build and the interactive catalog use the same data and visuals.
export const money=v=>new Intl.NumberFormat('ru-RU').format(v)+' ₽';
export const minPrice=p=>Math.min(...Object.values(p.price_tiers));
export const groupFor=p=>p.category==='headwear'?'headwear':p.category!=='apparel'?'accessories':p.id.startsWith('tshirt')?'tees':p.id.startsWith('bomber')?'bombers':'sweats';
export const productImages={
  'bag-shopper-favorit':'../catalog-2026/product-cards/shopper-open-flat-cutout-v2.webp','bag-shopper-gretta':'../catalog-2026/product-cards/shopper-open-flat-cutout-v2.webp','bag-shopper-zip-favorit':'../catalog-2026/product-cards/shopper-zip-flat-cutout-v2.webp','bag-shopper-zip-gretta':'../catalog-2026/product-cards/shopper-zip-flat-cutout-v2.webp',
  'bag-shoulder-oxford600':'../catalog-2026/product-cards/shoulder-bag-two-tone-cutout-v2.webp','bag-waist-oxford600':'../catalog-2026/product-cards/waist-bag-premium-smooth-v5.webp','backpack-drawstring-oxford600':'../catalog-2026/product-cards/fonbase-backpack-foreground-v2.webp','bag-shoes-oxford200':'../catalog-2026/product-cards/shoe-bag-straps-oxford200-v2.webp','pencil-case-oxford600':'../catalog-2026/product-cards/pencil-case-trio-premium-v1.webp','garment-bag-oxford300':'../catalog-2026/product-cards/garment-cover-oxford300-v2.webp',
  'tshirt-false-mesh-140':'tshirt-false-mesh-140-ai-cutout-v5.webp','tshirt-false-mesh-220':'tshirt-false-mesh-220-ai-cutout-v5.webp','tshirt-cotton-open-end-140':'tshirt-open-end-140-ai-cutout-v5.webp','tshirt-cotton-lycra-peigne-190':'tshirt-peigne-190-ai-cutout-v5.webp',
  'hoodie-3thread-fleece':'hoodie-3thread-fleece-ai-cutout-v5.webp','hoodie-3thread-loopback':'hoodie-3thread-loopback-ai-cutout-v5.webp','sweatshirt-2thread':'sweatshirt-2thread-ai-cutout-v5.webp','longsleeve-2thread':'longsleeve-2thread-ai-cutout-v5.webp','bomber-3thread-fleece':'bomber-3thread-fleece-cutout-v4.webp','bomber-3thread-loopback':'bomber-3thread-loopback-ai-cutout-v5.webp','panama-gretta':'panama-gretta-cutout-v2.webp'
};
export const apparelColors=[
  {id:'white',name:'Белый',tier:'стандарт',hex:'#f4f1e8',brightness:1.55,contrast:.78},
  {id:'black',name:'Чёрный',tier:'стандарт',hex:'#171717',brightness:.38,contrast:1.05},
  {id:'navy',name:'Тёмно-синий',tier:'стандарт',hex:'#1f3153',brightness:.72,contrast:.94},
  {id:'burgundy',name:'Бордо',tier:'премиум',hex:'#6e2433',brightness:.78,contrast:.9},
  {id:'emerald',name:'Глубокий зелёный',tier:'премиум',hex:'#17554c',brightness:.74,contrast:.9},
  {id:'sand',name:'Песочный',tier:'премиум',hex:'#b69a72',brightness:1.16,contrast:.82}
];
const colorProductIds=new Set(['bag-shopper-favorit','bag-shopper-gretta','bag-shopper-zip-favorit','bag-shopper-zip-gretta','bag-shoulder-oxford600']);
export const apparelMasks=Object.fromEntries(Object.entries(productImages).filter(([id])=>id.startsWith('tshirt')||id.startsWith('hoodie')||id.startsWith('sweatshirt')||id.startsWith('longsleeve')||id.startsWith('bomber')||id==='panama-gretta'||colorProductIds.has(id)).map(([id,image])=>[id,image.split('/').at(-1)]));
const defaultApparelColors={'tshirt-false-mesh-140':'white','tshirt-false-mesh-220':'navy','tshirt-cotton-open-end-140':'sand','tshirt-cotton-lycra-peigne-190':'burgundy','hoodie-3thread-fleece':'black','hoodie-3thread-loopback':'white','sweatshirt-2thread':'black','longsleeve-2thread':'white','bomber-3thread-fleece':'navy','bomber-3thread-loopback':'emerald','panama-gretta':'black','bag-shopper-favorit':'black','bag-shopper-gretta':'sand','bag-shopper-zip-favorit':'black','bag-shopper-zip-gretta':'sand','bag-shoulder-oxford600':'emerald'};
const apparelBaseBrightness={'tshirt-false-mesh-140':.78,'tshirt-false-mesh-220':.92,'tshirt-cotton-open-end-140':1.08,'tshirt-cotton-lycra-peigne-190':1.45,'hoodie-3thread-fleece':1.7,'hoodie-3thread-loopback':.8,'sweatshirt-2thread':1.4,'longsleeve-2thread':.8,'bomber-3thread-fleece':1.2,'bomber-3thread-loopback':1.08,'panama-gretta':1.08,'bag-shopper-favorit':1.5,'bag-shopper-gretta':1.28,'bag-shopper-zip-favorit':1.25,'bag-shopper-zip-gretta':1.25};
const pairedColorFilters={white:'grayscale(1) brightness(3.7) contrast(.62)',black:'grayscale(1) brightness(.5) contrast(1.1)',navy:'hue-rotate(78deg) saturate(.88) brightness(.76)',burgundy:'hue-rotate(180deg) saturate(1.2) brightness(.8)',emerald:'none',sand:'grayscale(1) sepia(1) saturate(1.2) brightness(1.65)'};
export const selectedApparelColors=new Map();
export const hasColorPicker=p=>p.category==='apparel'||p.id==='panama-gretta'||colorProductIds.has(p.id);
export const isPairedColorProduct=p=>p.id==='bag-shoulder-oxford600';
export const imageFor=p=>new URL((p.category==='apparel'||p.category==='headwear')?`/media/catalog-2026/product-cards/${productImages[p.id]}`:`/media/catalog-products/${productImages[p.id]}`,'https://alidika.ru').pathname;
export const selectedApparelColor=p=>apparelColors.find(color=>color.id===(selectedApparelColors.get(p.id)||defaultApparelColors[p.id]))||apparelColors[0];
export const apparelStyle=(p,color=selectedApparelColor(p))=>`--garment-mask:url('/media/catalog-2026/product-cards/${apparelMasks[p.id]}');--garment-color:${color.hex};--garment-brightness:${(color.brightness*(apparelBaseBrightness[p.id]||1)).toFixed(2)};--garment-contrast:${color.contrast};--paired-filter:${isPairedColorProduct(p)?pairedColorFilters[color.id]:'none'}`;
export const apparelMedia=(p,loading='lazy')=>`<div class="apparel-visual${isPairedColorProduct(p)?' paired-color-visual':''}" data-apparel-visual="${p.id}" style="${apparelStyle(p)}"><img class="garment-base" loading="${loading}" decoding="async" src="${imageFor(p)}" alt="Модель: ${p.name}; материал — ${p.material}">${isPairedColorProduct(p)?'':`<img class="garment-luma" loading="${loading}" decoding="async" src="${imageFor(p)}" alt="" aria-hidden="true"><span class="garment-hue" aria-hidden="true"></span>`}</div>`;
export const colorControls=p=>{const selected=selectedApparelColor(p);return `<div class="color-choice" data-color-choice="${p.id}"><span>Цвет: <strong data-color-name>${selected.name}</strong> · <small data-color-tier>${selected.tier}</small></span><div class="color-swatches" role="group" aria-label="Выбрать цвет ${p.name}">${apparelColors.map(color=>`<button type="button" class="color-swatch" data-color-product="${p.id}" data-apparel-color="${color.id}" data-color-tier="${color.tier}" style="--swatch:${color.hex}" aria-label="${color.name}, ${color.tier}" title="${color.name} · ${color.tier}" aria-pressed="${color.id===selected.id}"><span class="visually-hidden">${color.name}</span></button>`).join('')}</div></div>`};
const swatchFor=p=>p.material.includes('Оксфорд')?'oxford':p.material==='Фаворит'?'favorit':'gretta';
export const reasonFor=p=>{const i=p.id;if(i.includes('mesh-140'))return'Лёгкая спортивная база для массовых комплектов.';if(i.includes('mesh-220'))return'Более плотная спортивная футболка.';if(i.includes('open-end'))return'Доступный хлопок с фактурной поверхностью.';if(i.includes('peigne'))return'Гладкий прочёсанный хлопок с эластаном.';if(i.includes('2thread'))return'Лёгкий трикотажный слой для межсезонья.';if(i.includes('loopback'))return'Плотный футер с петлёй без пушистого начёса.';if(i.includes('fleece'))return'Тёплый вариант с начёсом.';if(p.material==='Фаворит')return'Плотнее Греты на 30 г/м², ощущается основательнее.';if(p.material==='Грета')return'Более доступная смесовая ткань.';if(p.material.includes('600'))return'Плотный Оксфорд с ПВХ-покрытием.';if(p.material.includes('300'))return'Практичный материал для чехлов.';if(p.material.includes('200'))return'Лёгкий Оксфорд для аксессуаров.';return'Базовая модель для фирменной коллекции.'};
export const detailsFor=p=>[p.material,p.composition,p.density_g_m2?`${p.density_g_m2} г/м²`:'',p.color_condition].filter(Boolean).join(' · ');
export const brandingFor=p=>p.material==='Фаворит'?'Для Фаворита подтверждены DTF и шелкография до 5 цветов.':p.color_condition==='Белая'&&p.composition==='100% полиэстер'?'Для белого полиэстера подходит сублимация; другие способы уточняются по макету.':p.material==='Грета'?'В исходном прайсе печать на Грете указана для белого и бежевого цветов; технологию уточним.':'Совместимость нанесения подтверждаем по материалу, цвету и макету перед запуском.';
export const isShopper=p=>p.id.includes('shopper');
export const productsForChoice=(items,choice)=>items.filter(p=>choice==='all'||(choice==='shoppers'?isShopper(p):choice==='bags'?p.category==='bags_accessories'&&!isShopper(p):groupFor(p)===choice));
export const priceTiers=p=>`<div class="tier-table">${Object.entries(p.price_tiers).map(([q,v],i,tiers)=>`<div class="tier ${i===tiers.length-1?'best':''}"><span>от ${q} шт.</span><strong>${money(v)}</strong></div>`).join('')}</div>`;
export const productCards=items=>items.map((p,index)=>`<article class="product-card" id="${p.id}" data-group="${groupFor(p)}" data-category="${p.category}"><div class="product-media" data-product-id="${p.id}" role="button" tabindex="0" aria-label="Открыть цены по тиражу: ${p.name}">${hasColorPicker(p)?apparelMedia(p,index<3?'eager':'lazy'):`<img loading="${index<3?'eager':'lazy'}" decoding="async" src="${imageFor(p)}" alt="Модель: ${p.name}; материал — ${p.material}">`}${hasColorPicker(p)?'':`<span class="material-swatch ${swatchFor(p)}" title="Материал: ${p.material}" aria-label="Образец материала: ${p.material}"></span>`}</div><div class="product-info"><p class="product-kicker">${detailsFor(p)}</p>${hasColorPicker(p)?colorControls(p):''}<div class="product-title"><h3>${p.name}</h3><span class="product-price">от ${money(minPrice(p))}/шт.</span></div><p>${reasonFor(p)}</p><details class="static-prices"><summary data-product-id="${p.id}">Цены по тиражу</summary>${priceTiers(p)}<p>${brandingFor(p)}</p><p>Цена за изделие без нанесения и упаковки. Итоговая стоимость уточняется после согласования заказа.</p><a href="#request">Запросить расчёт</a></details></div></article>`).join('');
export const serviceCards=items=>items.map(s=>`<article class="service-card"><strong>${s.name}</strong><b>+ ${money(s.price_per_item)}/шт.</b><p>${s.description||'Индивидуальная упаковка готового изделия'}</p></article>`).join('');
