const grid=document.querySelector('#product-grid'),serviceGrid=document.querySelector('#service-grid'),dialog=document.querySelector('#product-dialog'),dialogContent=document.querySelector('#dialog-content'),productSelect=document.querySelector('#request-product');let catalog={products:[],branding:[]},activeFilter='all';
const heroCases={ruki:{src:'/media/catalog-2026/08_ruki_vverh_bar_apparel_capsule_ai.webp',alt:'Визуализация корпоративной коллекции для Руки ВВерх! Бар',caption:'Визуализация · Руки ВВерх! Бар'},magnit:{src:'/media/catalog-2026/05_magnit_apteka_accessory_bag_ai_v3.webp',alt:'Визуализация фирменных пеналов для Магнит Аптеки',caption:'Визуализация · Магнит Аптека'},gazprom:{src:'/media/works-rendered/tshirt-gazprom-team-render-v2.webp',alt:'Визуализация команды в синих фирменных футболках для Газпром трансгаз',caption:'Визуализация · Газпром трансгаз',fit:'contain'},fonbase:{src:'/media/catalog-2026/07_fonbase_textile_set_ai.webp',alt:'Визуализация фирменного текстильного набора FONBASE',caption:'Визуализация · FONBASE'},uds:{src:'/media/catalog-2026/09_uds_capsule_ai.webp',alt:'Визуализация фирменной капсулы UDS: худи, шоппер, поясная сумка и текстиль',caption:'Визуализация · UDS'}};
function showHeroCase(key){const item=heroCases[key],image=document.querySelector('#hero-case-image'),figure=image?.closest('.hero-visual'),caption=document.querySelector('#hero-case-caption');if(!item||!image||!figure||!caption)return;image.src=item.src;image.alt=item.alt;caption.textContent=item.caption;figure.classList.toggle('hero-contain',item.fit==='contain');figure.style.setProperty('--hero-bg',`url('${item.src}')`);document.querySelectorAll('[data-hero-case]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.heroCase===key)))}
document.addEventListener('click',event=>{const button=event.target.closest('[data-hero-case]');if(button)showHeroCase(button.dataset.heroCase)});
document.addEventListener('load',event=>{if(event.target.matches?.('.garment-luma'))event.target.parentElement.classList.add('color-ready')},true);
const money=v=>new Intl.NumberFormat('ru-RU').format(v)+' ₽',minPrice=p=>Math.min(...Object.values(p.price_tiers));
const groupFor=p=>p.category==='headwear'?'headwear':p.category!=='apparel'?'accessories':p.id.startsWith('tshirt')?'tees':p.id.startsWith('bomber')?'bombers':'sweats';
const productImages={
  'bag-shopper-favorit':'../catalog-2026/product-cards/shopper-plain-premium-v1.webp','bag-shopper-gretta':'../catalog-2026/product-cards/shopper-light-muted-clay-v2.webp','bag-shopper-zip-favorit':'../catalog-2026/product-cards/shopper-zip-black-premium-v1.webp','bag-shopper-zip-gretta':'../catalog-2026/product-cards/shopper-zip-muted-clay-premium-v1.webp',
  'bag-shoulder-oxford600':'../catalog-2026/product-cards/crossbody-bags-premium-smooth-rotated-v6.webp','bag-waist-oxford600':'../catalog-2026/product-cards/waist-bag-premium-smooth-v5.webp','backpack-drawstring-oxford600':'../catalog-2026/product-cards/fonbase-backpack-foreground-v2.webp','bag-shoes-oxford200':'../catalog-2026/product-cards/shoe-bag-straps-oxford200-v2.webp','pencil-case-oxford600':'../catalog-2026/product-cards/pencil-case-trio-premium-v1.webp','garment-bag-oxford300':'../catalog-2026/product-cards/garment-cover-oxford300-v2.webp',
  'tshirt-false-mesh-140':'tshirt-false-mesh-140-ai-cutout-v5.webp','tshirt-false-mesh-220':'tshirt-false-mesh-220-ai-cutout-v5.webp','tshirt-cotton-open-end-140':'tshirt-open-end-140-ai-cutout-v5.webp','tshirt-cotton-lycra-peigne-190':'tshirt-peigne-190-ai-cutout-v5.webp',
  'hoodie-3thread-fleece':'hoodie-3thread-fleece-ai-cutout-v5.webp','hoodie-3thread-loopback':'hoodie-3thread-loopback-ai-cutout-v5.webp','sweatshirt-2thread':'sweatshirt-2thread-ai-cutout-v5.webp','longsleeve-2thread':'longsleeve-2thread-ai-cutout-v5.webp','bomber-3thread-fleece':'bomber-3thread-fleece-cutout-v4.webp','bomber-3thread-loopback':'bomber-3thread-loopback-ai-cutout-v5.webp','panama-gretta':'panama-gretta-cutout-v2.webp'
};
const apparelColors=[
  {id:'white',name:'Белый',tier:'стандарт',hex:'#f4f1e8',brightness:1.55,contrast:.78},
  {id:'black',name:'Чёрный',tier:'стандарт',hex:'#171717',brightness:.38,contrast:1.05},
  {id:'navy',name:'Тёмно-синий',tier:'стандарт',hex:'#1f3153',brightness:.72,contrast:.94},
  {id:'burgundy',name:'Бордо',tier:'премиум',hex:'#6e2433',brightness:.78,contrast:.9},
  {id:'emerald',name:'Глубокий зелёный',tier:'премиум',hex:'#17554c',brightness:.74,contrast:.9},
  {id:'sand',name:'Песочный',tier:'премиум',hex:'#b69a72',brightness:1.16,contrast:.82}
];
const apparelMasks={'tshirt-false-mesh-140':'tshirt-false-mesh-140-ai-cutout-v5.webp','tshirt-false-mesh-220':'tshirt-false-mesh-220-ai-cutout-v5.webp','tshirt-cotton-open-end-140':'tshirt-open-end-140-ai-cutout-v5.webp','tshirt-cotton-lycra-peigne-190':'tshirt-peigne-190-ai-cutout-v5.webp','hoodie-3thread-fleece':'hoodie-3thread-fleece-ai-cutout-v5.webp','hoodie-3thread-loopback':'hoodie-3thread-loopback-ai-cutout-v5.webp','sweatshirt-2thread':'sweatshirt-2thread-ai-cutout-v5.webp','longsleeve-2thread':'longsleeve-2thread-ai-cutout-v5.webp','bomber-3thread-fleece':'bomber-3thread-fleece-cutout-v4.webp','bomber-3thread-loopback':'bomber-3thread-loopback-ai-cutout-v5.webp','panama-gretta':'panama-gretta-cutout-v2.webp'};
const defaultApparelColors={'tshirt-false-mesh-140':'white','tshirt-false-mesh-220':'navy','tshirt-cotton-open-end-140':'sand','tshirt-cotton-lycra-peigne-190':'burgundy','hoodie-3thread-fleece':'black','hoodie-3thread-loopback':'white','sweatshirt-2thread':'black','longsleeve-2thread':'white','bomber-3thread-fleece':'navy','bomber-3thread-loopback':'emerald','panama-gretta':'black'};
const apparelBaseBrightness={'tshirt-false-mesh-140':.78,'tshirt-false-mesh-220':.92,'tshirt-cotton-open-end-140':1.08,'tshirt-cotton-lycra-peigne-190':1.45,'hoodie-3thread-fleece':1.7,'hoodie-3thread-loopback':.8,'sweatshirt-2thread':1.4,'longsleeve-2thread':.8,'bomber-3thread-fleece':1.2,'bomber-3thread-loopback':1.08,'panama-gretta':1.08};
const selectedApparelColors=new Map();let requestColor='';
const temporaryVisuals=new Set();
const hasColorPicker=p=>p.category==='apparel'||p.id==='panama-gretta';
const imageFor=p=>(p.category==='apparel'||p.category==='headwear')?`/media/catalog-2026/product-cards/${productImages[p.id]}`:`/media/catalog-products/${productImages[p.id]}`;
const selectedApparelColor=p=>apparelColors.find(color=>color.id===(selectedApparelColors.get(p.id)||defaultApparelColors[p.id]))||apparelColors[0];
const apparelStyle=(p,color=selectedApparelColor(p))=>`--garment-mask:url('/media/catalog-2026/product-cards/${apparelMasks[p.id]}');--garment-color:${color.hex};--garment-brightness:${(color.brightness*(apparelBaseBrightness[p.id]||1)).toFixed(2)};--garment-contrast:${color.contrast}`;
const apparelMedia=(p,loading='lazy')=>`<div class="apparel-visual" data-apparel-visual="${p.id}" style="${apparelStyle(p)}"><img class="garment-base" loading="${loading}" decoding="async" src="${imageFor(p)}" alt="Визуализация модели: ${p.name}; материал — ${p.material}"><img class="garment-luma" loading="${loading}" decoding="async" src="${imageFor(p)}" alt="" aria-hidden="true"><span class="garment-hue" aria-hidden="true"></span></div>`;
const colorControls=p=>{const selected=selectedApparelColor(p);return `<div class="color-choice" data-color-choice="${p.id}"><span>Цвет: <strong data-color-name>${selected.name}</strong> · <small data-color-tier>${selected.tier}</small></span><div class="color-swatches" role="group" aria-label="Выбрать цвет ${p.name}">${apparelColors.map(color=>`<button type="button" class="color-swatch" data-color-product="${p.id}" data-apparel-color="${color.id}" data-color-tier="${color.tier}" style="--swatch:${color.hex}" aria-label="${color.name}, ${color.tier}" title="${color.name} · ${color.tier}" aria-pressed="${color.id===selected.id}"><span class="visually-hidden">${color.name}</span></button>`).join('')}</div></div>`};
function setApparelColor(productId,colorId){const p=catalog.products.find(item=>item.id===productId),color=apparelColors.find(item=>item.id===colorId);if(!p||!color)return;selectedApparelColors.set(productId,colorId);document.querySelectorAll(`[data-apparel-visual="${productId}"]`).forEach(visual=>visual.setAttribute('style',apparelStyle(p,color)));document.querySelectorAll(`[data-color-choice="${productId}"]`).forEach(choice=>{choice.querySelector('[data-color-name]').textContent=color.name;choice.querySelector('[data-color-tier]').textContent=color.tier;choice.querySelectorAll('[data-apparel-color]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.apparelColor===colorId)))})}
const swatchFor=p=>p.category==='apparel'?'tshirt':p.material.includes('Оксфорд')?'oxford':p.material==='Фаворит'?'favorit':'gretta';
const reasonFor=p=>{const i=p.id;if(i.includes('mesh-140'))return'Лёгкая спортивная база для массовых комплектов.';if(i.includes('mesh-220'))return'Более плотная спортивная футболка.';if(i.includes('open-end'))return'Доступный хлопок с фактурной поверхностью.';if(i.includes('peigne'))return'Гладкий прочёсанный хлопок с эластаном.';if(i.includes('2thread'))return'Лёгкий трикотажный слой для межсезонья.';if(i.includes('loopback'))return'Плотный футер с петлёй без пушистого начёса.';if(i.includes('fleece'))return'Тёплый вариант с начёсом.';if(p.material==='Фаворит')return'Плотнее Греты на 30 г/м², ощущается основательнее.';if(p.material==='Грета')return'Более доступная смесовая ткань.';if(p.material.includes('600'))return'Плотный Оксфорд с ПВХ-покрытием.';if(p.material.includes('300'))return'Практичный материал для чехлов.';if(p.material.includes('200'))return'Лёгкий Оксфорд для аксессуаров.';return'Базовая модель для фирменной коллекции.'};
const detailsFor=p=>[p.material,p.composition,p.density_g_m2?`${p.density_g_m2} г/м²`:'',p.color_condition].filter(Boolean).join(' · ');
const brandingFor=p=>p.material==='Фаворит'?'Для Фаворита подтверждены DTF и шелкография до 5 цветов.':p.color_condition==='Белая'&&p.composition==='100% полиэстер'?'Для белого полиэстера подходит сублимация; другие способы уточняются по макету.':p.material==='Грета'?'В исходном прайсе печать на Грете указана для белого и бежевого цветов; технологию уточним.':'Совместимость нанесения подтверждаем по материалу, цвету и макету перед запуском.';
const pencilImages=[['/media/catalog-2026/product-cards/pencil-case-green.webp','Зелёный пенал с нанесением'],['/media/catalog-2026/product-cards/pencil-case-beige.webp','Бежевый пенал с нанесением'],['/media/catalog-2026/product-cards/pencil-case-blue.webp','Синий пенал с нанесением']];
const productMedia=p=>p.id==='pencil-case-oxford600'?`<div class="pencil-carousel" data-carousel-index="0" style="position:relative;align-self:start;background:#f3eee6"><div class="pencil-slides">${pencilImages.map(([src,alt],i)=>`<img loading="${i?'lazy':'eager'}" decoding="async" src="${src}" alt="${alt}" style="width:100%;aspect-ratio:1/1;object-fit:cover;display:${i?'none':'block'}">`).join('')}</div><button type="button" data-carousel-prev aria-label="Предыдущий пенал" style="position:absolute;left:12px;top:45%;width:44px;height:44px;border:0;border-radius:50%;background:#fff;font-size:24px;cursor:pointer">←</button><button type="button" data-carousel-next aria-label="Следующий пенал" style="position:absolute;right:12px;top:45%;width:44px;height:44px;border:0;border-radius:50%;background:#fff;font-size:24px;cursor:pointer">→</button><div class="pencil-dots" style="position:absolute;left:0;right:0;bottom:12px;display:flex;justify-content:center;gap:7px">${pencilImages.map((_,i)=>`<button type="button" data-carousel-dot="${i}" aria-label="Показать пенал ${i+1}" style="width:11px;height:11px;padding:0;border:1px solid #181817;border-radius:50%;background:${i?'#fff':'#181817'}"></button>`).join('')}</div></div>`:hasColorPicker(p)?apparelMedia(p,'eager'):`<img loading="eager" decoding="async" src="${imageFor(p)}" alt="Визуализация: ${p.name}">`;
function renderProducts(){if(grid)grid.innerHTML=catalog.products.map(p=>`<article class="product-card" data-group="${groupFor(p)}" data-category="${p.category}"><div class="product-media" data-product-id="${p.id}" role="button" tabindex="0" aria-label="Открыть цены по тиражу: ${p.name}">${hasColorPicker(p)?apparelMedia(p):`<img loading="lazy" decoding="async" src="${imageFor(p)}" alt="Визуализация модели: ${p.name}; материал — ${p.material}">`}${hasColorPicker(p)||groupFor(p)==='tees'?'':`<span class="material-swatch ${swatchFor(p)}" title="Материал: ${p.material}" aria-label="Образец материала: ${p.material}"></span>`}${temporaryVisuals.has(p.id)?'<small>Временный визуал категории</small>':''}</div><div class="product-info"><p class="product-kicker">${detailsFor(p)}</p>${hasColorPicker(p)?colorControls(p):''}<div class="product-title"><h3>${p.name}</h3><span class="product-price">от ${money(minPrice(p))}/шт.</span></div><p>${reasonFor(p)}</p><button type="button" data-product-id="${p.id}">Цены по тиражу</button></div></article>`).join('');setProductOptions(catalog.products,'Выбрать из каталога');applyFilter(activeFilter)}
function setProductOptions(items,label){productSelect.innerHTML=`<option value="">${label}</option>`+items.map(p=>`<option value="${p.name} — ${p.material}">${p.name} — ${p.material}</option>`).join('')}
const isShopper=p=>p.id.includes('shopper');
function productsForChoice(choice){return catalog.products.filter(p=>choice==='shoppers'?isShopper(p):choice==='bags'?p.category==='bags_accessories'&&!isShopper(p):groupFor(p)===choice)}
function renderServices(){serviceGrid.innerHTML=catalog.branding.map(s=>`<article class="service-card"><strong>${s.name}</strong><b>+ ${money(s.price_per_item)}/шт.</b><p>${s.description||'Индивидуальная упаковка готового изделия'}</p></article>`).join('')}
function openProduct(id){const p=catalog.products.find(x=>x.id===id);if(!p)return;const tiers=Object.entries(p.price_tiers);dialogContent.innerHTML=`<div class="dialog-body">${productMedia(p)}<div class="dialog-copy"><p class="eyebrow">Цена за изделие</p><h2>${p.name}</h2><p><strong>${detailsFor(p)}</strong></p>${hasColorPicker(p)?colorControls(p):''}<p>${reasonFor(p)}</p><div class="tier-table">${tiers.map(([q,v],i)=>`<div class="tier ${i===tiers.length-1?'best':''}"><span>от ${q} шт.</span><strong>${money(v)}</strong></div>`).join('')}</div><p class="dialog-note"><strong>Нанесение:</strong> ${brandingFor(p)}<br>Финальная стоимость зависит от подтверждённой комплектации.</p><button class="button primary dialog-action" type="button" data-add-request="${p.id}">Добавить в запрос</button></div></div>`;dialog.showModal()}
function showPencilSlide(index){const carousel=dialog.querySelector('.pencil-carousel');if(!carousel)return;const slides=[...carousel.querySelectorAll('.pencil-slides img')],dots=[...carousel.querySelectorAll('[data-carousel-dot]')],next=(index+slides.length)%slides.length;carousel.dataset.carouselIndex=next;slides.forEach((img,i)=>img.style.display=i===next?'block':'none');dots.forEach((dot,i)=>dot.style.background=i===next?'#181817':'#fff')}
function applyFilter(f){activeFilter=f;document.querySelectorAll('.filters button').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));document.querySelectorAll('.product-card').forEach(c=>{const p=catalog.products.find(item=>item.id===c.querySelector('[data-product-id]')?.dataset.productId);c.hidden=!(f==='all'||f===c.dataset.category||f===c.dataset.group||(f==='accessories'&&c.dataset.category==='bags_accessories')||(f==='shoppers'&&p&&isShopper(p))||(f==='bags'&&p&&p.category==='bags_accessories'&&!isShopper(p)))})}
fetch('/catalog-2026.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{catalog=d;renderProducts();renderServices()}).catch(()=>{if(grid)grid.innerHTML='<p>Не удалось загрузить каталог. Обнови страницу или напиши нам в VK — поможем подобрать изделие.</p>';productSelect.innerHTML='<option>Напиши нам в VK — поможем выбрать</option>'});
document.addEventListener('click',e=>{const colorButton=e.target.closest('[data-apparel-color]');if(colorButton){e.preventDefault();e.stopPropagation();setApparelColor(colorButton.dataset.colorProduct,colorButton.dataset.apparelColor);return}const p=e.target.closest('[data-product-id]');if(p)openProduct(p.dataset.productId);const f=e.target.closest('[data-filter]');if(f)applyFilter(f.dataset.filter);const l=e.target.closest('[data-filter-link]');if(l)setTimeout(()=>applyFilter(l.dataset.filterLink),0);const choice=e.target.closest('[data-category-choice]');if(choice){applyFilter(choice.dataset.categoryChoice);setProductOptions(productsForChoice(choice.dataset.categoryChoice),`Выбрать: ${choice.querySelector('strong')?.textContent||choice.textContent.trim()}`)}const carousel=e.target.closest('.pencil-carousel');if(e.target.closest('[data-carousel-prev]'))showPencilSlide(Number(carousel.dataset.carouselIndex)-1);if(e.target.closest('[data-carousel-next]'))showPencilSlide(Number(carousel.dataset.carouselIndex)+1);const dot=e.target.closest('[data-carousel-dot]');if(dot)showPencilSlide(Number(dot.dataset.carouselDot));const a=e.target.closest('[data-add-request]');if(a){const item=catalog.products.find(x=>x.id===a.dataset.addRequest);productSelect.value=`${item.name} — ${item.material}`;requestColor=hasColorPicker(item)?selectedApparelColor(item).name:'';dialog.close();document.querySelector('#request').scrollIntoView({behavior:'smooth'})}});
document.addEventListener('keydown',e=>{const media=e.target.closest('.product-media[data-product-id]');if(media&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openProduct(media.dataset.productId)}});
productSelect.addEventListener('change',()=>{requestColor='';if(productSelect.value.startsWith('Пенал —'))openProduct('pencil-case-oxford600')});
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
function requestText(){const lines=['Здравствуйте! Хочу получить расчёт АЛИДИКИ.'],product=productSelect.value,quantity=document.querySelector('#request-quantity').value.trim(),branding=document.querySelector('#request-branding').value,comment=document.querySelector('#request-comment').value.trim();if(product)lines.push(`Изделие: ${product}.`);if(requestColor)lines.push(`Цвет: ${requestColor}.`);if(quantity)lines.push(`Количество: ${quantity} шт.`);lines.push(`Нанесение: ${branding}.`);if(comment)lines.push(`Комментарий: ${comment}`);lines.push('Подтвердите, пожалуйста, материал, комплектацию и итоговую стоимость.');return lines.join('\n')}
function copyRequestText(text){const field=document.createElement('textarea');field.value=text;field.setAttribute('readonly','');field.style.cssText='position:fixed;left:-9999px;top:0';document.body.append(field);field.select();try{document.execCommand('copy')}finally{field.remove()}if(navigator.clipboard?.writeText)navigator.clipboard.writeText(text).catch(()=>{})}
function copyAndOpenMessenger(url){copyRequestText(requestText());window.location.assign(url)}
document.querySelector('#request-form').addEventListener('submit',e=>e.preventDefault());
document.querySelector('#send-vk').addEventListener('click',()=>copyAndOpenMessenger('https://vk.me/alidika1'));
document.querySelector('#send-max').addEventListener('click',()=>copyAndOpenMessenger('https://web.max.ru/210087080'));
